name: Create PR on schedule

on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  createPullRequest:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install PostgreSQL
      run: sudo apt-get -yqq install libpq-dev

    - name: Set up Database
      run: |
        sudo service postgresql start
        sudo -u postgres psql -c "CREATE USER rails WITH PASSWORD 'rails';"
        sudo -u postgres psql -c "DROP DATABASE IF EXISTS github_actions_test;"
        sudo -u postgres psql -c "CREATE DATABASE github_actions_test OWNER rails;"


    - name: Install dependencies
      run: bundle install

    - name: Create file
      run: |
        bin/rails db:setup
        bin/rails generate migrate create_users name:string
        bin/rails db:migrate
      env:
        DATABASE_URL: postgres://rails:rails@localhost/github_actions_test

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update data
        title: Update data
        body: >
          This is an auto-generated PR to update the data
        branch: auto-pr-data-update-${{ github.run_id }}
        add-paths: db/migrate
        base: main
