name: Create PR on schedule

on:
  schedule:
  - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  DATABASE_URL: postgres://runner:runner@localhost/action_development
  RAILS_ENV: development
  POSTGRES_HOST: postgres
  POSTGRES_PORT: 5432

jobs:
  createPullRequest:
    permissions: write-all
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: bundle install

    - name: Set up Database
      run: |
        PGPASSWORD='postgres'
        PGPASSWORD='postgres' psql -h localhost -U postgres  -c "CREATE USER runner WITH PASSWORD 'runner';"
        PGPASSWORD='postgres' psql -h localhost -U postgres  -c "ALTER USER runner CREATEDB;"
        PGPASSWORD='postgres' psql -h localhost -U postgres  -c "DROP DATABASE IF EXISTS action_development;"
        PGPASSWORD='postgres' psql -h localhost -U postgres  -c "CREATE DATABASE action_development OWNER runner;"

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Create file
      run: |
        bin/rails db:setup
        bin/rails generate migration create_users name:string
        bin/rails db:migrate

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update data
        title: Update data
        body: >
          This is an auto-generated PR to update the data
        branch: auto-pr-data-update-${{ github.run_id }}
        add-paths: db/*

        base: main
